Repository KSU-DB/Twitter-Clone-BackEnd, pull requests merged in 2019-12, with the labels that each got.

#12 보안 적용
  twitterclone/build.gradle
  twitterclone/src/main/java/me/dblab/twitterclone/TwittercloneApplication.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/Account.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/Role.java
  twitterclone/src/main/java/me/dblab/twitterclone/common/AppProperties.java
  twitterclone/src/main/java/me/dblab/twitterclone/common/Constants.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/SecurityConfig.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/SecurityContextRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/TokenProvider.java
  twitterclone/src/main/resources/accout.properties
  twitterclone/src/main/resources/application.properties
  twitterclone/src/main/resources/application.yml
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/AppPropertiesTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/config/SecurityConfigTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetRepositoryTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetTest.java
Labels: enhancement

#14 README 수정
  README.md
Labels: enhancement

#19 Create TweetController, Service
  twitterclone/build.gradle
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/common/AppProperties.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/main/resources/application.yml
  twitterclone/src/test/java/me/dblab/twitterclone/common/AuthServerConfigTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
Labels: enhancement

#21 Refactoring Account
  twitterclone/build.gradle
  twitterclone/src/main/java/me/dblab/twitterclone/TwittercloneApplication.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountDto.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountValidator.java
  twitterclone/src/main/java/me/dblab/twitterclone/common/AppProperties.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/AppConfig.java
  twitterclone/src/main/resources/application.yml
Labels: refactoring

#24 create basecontrollertest
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/AuthServerConfigTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/BaseControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
Labels: refactoring

#25 follow 구현
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/Follow.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowController.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowService.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
Labels: enhancement

#26 12/08
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/resources/application.yml
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
Labels: refactoring

#29 create tweetDto, validator
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetDto.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetValidator.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/BaseControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetValidatorTest.java
Labels: enhancement

#32 resolve #31
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetValidatorTest.java
Labels: enhancement

#35 issue #33
  twitterclone/src/main/java/me/dblab/twitterclone/config/SecurityConfig.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/config/SecurityConfigTest.java
Labels: enhancement

#34 Create Favorite
  twitterclone/src/main/java/me/dblab/twitterclone/account/Account.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/Favorite.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetRepository.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/BaseControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteTest.java
Labels: enhancement

#38 issue #37
  twitterclone/src/main/java/me/dblab/twitterclone/account/Account.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
Labels: bug, invalid

#40 lombok 사용해서 코드 양 줄이기
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/SecurityConfig.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/SecurityContextRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowController.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/AppPropertiesTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetRepositoryTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetTest.java
Labels: refactoring

#41 create Favorite(Get, Delete) & Test
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
Labels: enhancement, refactoring

#42 issue #39
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
Labels: bug

#45 issue #44
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowController.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
Labels: enhancement

#46 update readme
  README.md
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/SecurityContextRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/TokenProvider.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
Labels: refactoring

#47 Account 유효성 검사
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountValidator.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
Labels: refactoring

#49 issue #48
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/Jwt.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/config/SecurityConfigTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetRepositoryTest.java
Labels: enhancement

#51 Refactoring
  twitterclone/src/main/java/me/dblab/twitterclone/account/Account.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountDto.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountValidator.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/Role.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/AuthenticationManager.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/jwt/TokenProvider.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowController.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/follow/FollowService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetValidator.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountValidateTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/AppPropertiesTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/common/BaseControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/follow/FollowControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetRepositoryTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetValidatorTest.java
Labels: refactoring

#52 README 수정
  README.md
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/main/java/me/dblab/twitterclone/config/SecurityConfig.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
Labels: refactoring

#53 delete cors test
  twitterclone/src/test/java/me/dblab/twitterclone/config/SecurityConfigTest.java
Labels: refactoring

#55 Create Hashtag
  twitterclone/src/main/java/me/dblab/twitterclone/common/AppProperties.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/Tweet.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetController.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetValidator.java
  twitterclone/src/main/resources/application.yml
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetControllerTest.java
  twitterclone/src/test/java/me/dblab/twitterclone/tweet/TweetValidatorTest.java
Labels: enhancement
