Repository KSU-DB/Twitter-Clone-BackEnd, pull requests merged in 2020-01, with the labels that each got.

#59 Create Explore
  twitterclone/src/main/java/me/dblab/twitterclone/explore/Explore.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreController.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreDto.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreService.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreValidator.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetService.java
  twitterclone/src/test/java/me/dblab/twitterclone/explore/ExploreControllerTests.java
Labels: enhancement

#61 Explore 수정
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreController.java
  twitterclone/src/main/java/me/dblab/twitterclone/explore/ExploreService.java
  twitterclone/src/main/java/me/dblab/twitterclone/tweet/TweetRepository.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
Labels: refactoring

#63 Password 반환안시키기
  twitterclone/src/main/java/me/dblab/twitterclone/account/Account.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountController.java
  twitterclone/src/main/java/me/dblab/twitterclone/account/AccountService.java
  twitterclone/src/test/java/me/dblab/twitterclone/account/AccountControllerTests.java
Labels: refactoring

#65 좋아요 버그 수정
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteController.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteRepository.java
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
Labels: bug, refactoring

#66 front 요구사항
  twitterclone/src/main/java/me/dblab/twitterclone/favorite/FavoriteService.java
  twitterclone/src/test/java/me/dblab/twitterclone/favorite/FavoriteControllerTests.java
Labels: enhancement
